### ISSUE TITLE
issues to change currentIndex and change animation !

### ISSUE THREAD

**Issue by EhsanBrd** [pedromassango/titled_navigation_bar#17]
how can we change current index ?!
it's my code

class _MainNavigationBarState extends State<MainNavigationBar> {
  int currentPage = 0;

  GlobalKey bottomNavigationKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(color: Colors.white),
        child: Center(
          child: _getPage(currentPage),
        ),
      ),
      bottomNavigationBar: TitledBottomNavigationBar(
          currentIndex: 0, // Use this to update the Bar giving a position
          onTap: (index) => _onTabTapped(index),
          key: bottomNavigationKey,
          inactiveColor: Colors.grey,
          activeColor: Colors.black,
          reverse: true,
          curve: Curves.easeIn,
          items: [
            TitledNavigationBarItem(title: 'Home', icon: Icons.home),
            TitledNavigationBarItem(title: 'Search', icon: Icons.search),
            TitledNavigationBarItem(title: 'Basket', icon: Icons.shopping_basket),
            TitledNavigationBarItem(title: 'Profile', icon: Icons.person_outline),
          ]
      )

    );
  }

  void _onTabTapped(int index) {
    setState(() {
      currentPage = index;
    }); 
![9-18-2019 8-13-36 PM](https://user-images.githubusercontent.com/25132414/65163886-102b7380-da51-11e9-925f-56526c105861.gif)

  }

  _getPage(int page) {
    switch (page) {
      case 0:
        return Directionality(textDirection: TextDirection.rtl, child: HomeScreen());
      case 1:
        return Directionality(textDirection: TextDirection.rtl, child: Search());
      case 2:
        return Directionality(textDirection: TextDirection.rtl, child: Basket());
      case 3:
        return Directionality(textDirection: TextDirection.rtl, child: Profile());
      default:
        return Container();
    }
  }

**Comment by pedromassango** [comment]
Use the param `currentIndex` in the `TitledBottomNavigationBar` to change the current index

**Comment by EhsanBrd** [comment]
> Use the param `currentIndex` in the `TitledBottomNavigationBar` to change the current index.
> 
> Please feel free to reopen this issue if you still having trouble

Thank'sman , but did you see my code ?!
i use current index to change the index , but the animation of changing index not work !
swap animation bro not work !
changing index work well but not doing with animation , as my giff shows.

**Comment by pedromassango** [comment]
I saw your code and if you note, you are setting 0 to the `currentIndex` parameter.

**Comment by EhsanBrd** [comment]
yes it's set on **0** , but my issues here to when i program '**onTap**' parameters for change index , my index change when i use **setState** but the animation of tabbar not work to show selected index.
see my gif preview.

**Comment by pedromassango** [comment]
Note that `currentIndex` should be updated to animate the tabbar to the desired position. Try this:

use `currentIndex: currentPage` it should work

**Comment by EhsanBrd** [comment]
> Note that `currentIndex` should be updated to animate the tabbar to the desired position. Try this:
> 
> use `currentIndex: currentPage` it should work

Thank's bro , **it's work**

**Comment by hathanhoai** [comment]
@EhsanBrd 
I had the same problem and my solution was to remove setState() method. It worked.

**Comment by hathanhoai** [comment]
Because when you call the setState function, your screen is being reset, so the state hasn't changed

**Comment by EhsanBrd** [comment]
> @EhsanBrd
> I had the same problem and my solution was to remove setState() method. It worked.

Thank you bro , yes it's worked...
