### ISSUE TITLE
Ability to use a widget rather than a TitledNavBarItem?

### ISSUE THREAD

**Issue by YaarPatandarAA** [pedromassango/titled_navigation_bar#19]
Just a curious thought, if it is possible to use a widget with height and width constraints as a bottom nav bar item.

I cam across this while optimizing my app for iPad, I have a sliding panel for my Music Player screen. Looking at how Apple implemented their sliding panel for Music Player screen it is as a item in the bottom nav bar.
![27505-41204-Apple-Music-iPad---Singles-and-EPs-separated-l](https://user-images.githubusercontent.com/23144920/68405973-dfed8080-0135-11ea-8684-be582fbe2b04.jpg)

**Comment by VictorUvarov** [comment]
Maybe these widgets will help you. [ConstrainedBox](https://api.flutter.dev/flutter/widgets/ConstrainedBox-class.html) and [SizedBox](https://api.flutter.dev/flutter/widgets/SizedBox-class.html)

**Comment by pedromassango** [comment]
Since replacing `TitledNavBarItem` with a different widget would break this package this feature will not be add. Please fell free to forak and apply your required changes.
