### ISSUE TITLE
Internal SafeArea is generating unexpected bottom space

### ISSUE THREAD

**Issue by netojose** [pedromassango/titled_navigation_bar#21]
[This internal SafeArea](https://github.com/pedromassango/titled_navigation_bar/blob/master/lib/src/navigation_bar.dart#L67) is generating an unexpected space between bottom bar and screen end:

![image](https://user-images.githubusercontent.com/134008/78463978-0ebb5300-76e4-11ea-9639-eea3263797b8.png)

**Comment by alimhaq** [comment]
Hi @pedromassango, any updates on this? We would really appreciate a fix on this as we are launching our app soon and are facing the same issue.

**Comment by pedromassango** [comment]
Yes, going to fix it this Saturday
