### ISSUE TITLE
Cant remove the bottom bar even though I intend to disposing it.

### ISSUE THREAD

**Issue by ricky20121981** [pedromassango/titled_navigation_bar#35]
I post the picture in here to say it all
![pic0](https://user-images.githubusercontent.com/83386058/116500822-8ce32c80-a8d9-11eb-83e0-bc00a2bbc931.png)

so I am gonna log in

![pic1](https://user-images.githubusercontent.com/83386058/116500848-9c627580-a8d9-11eb-90cb-ae67d6bdf013.png)

this is what inside after log in, I move to profile tab with exit

![pic2](https://user-images.githubusercontent.com/83386058/116500907-ba2fda80-a8d9-11eb-8cde-70f02a0b8f44.png)

can't seem to dispose the titled navigation bar literally :p 

here is my code for that bar.

`class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final int _pageCount = 5;
  int _pageIndex = 0;
  final List<TitledNavigationBarItem> items = [
    TitledNavigationBarItem(title: Text('Home'), icon: Icons.home),
    TitledNavigationBarItem(title: Text('Search'), icon: Icons.search),
    TitledNavigationBarItem(title: Text('Histori'), icon: Icons.alarm_sharp),
    TitledNavigationBarItem(title: Text('Keranjang'), icon: Icons.shopping_cart_outlined),
    TitledNavigationBarItem(title: Text('Profil'), icon: Icons.person_outline),
  ];
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: _body(),
        bottomNavigationBar: _bottomNavigationBar(),
      ),
    );
  }

  Widget _body() {
    return Stack(
      children: List<Widget>.generate(_pageCount, (int index) {
        return IgnorePointer(
          ignoring: index != _pageIndex,
          child: Opacity(
            opacity: _pageIndex == index ? 1.0 : 0.0,
            child: Navigator(
              onGenerateRoute: (RouteSettings settings) {
                return new MaterialPageRoute(
                  builder: (_) => _page(index),
                  settings: settings,
                );
              },
            ),
          ),
        );
      }),
    );
  }

  Widget _page(int index) {
    switch (index) {
      case 0:
        return Home2();
      case 1:
        return search();
      case 2:
        return histori();
      case 3:
        return Keranjang();
      case 4:
        return profil();
    }
  }

  TitledBottomNavigationBar _bottomNavigationBar() {
    final theme = Theme.of(context);
    return new TitledBottomNavigationBar(
      currentIndex: _pageIndex,
        onTap: (index){
          setState(() {
      _pageIndex = index;});
          },
        items: items);
  }
}`

**and here just the exit code from profile class dart**

`class profil extends StatefulWidget {
  @override
  _profilState createState() => _profilState();
}

class _profilState extends State<profil> {
  @override
  Widget build(BuildContext context) {
    final deviceSize = MediaQuery.of(context).size;
    return  Scaffold(
      body: SingleChildScrollView(
        child: Container(
          margin: EdgeInsets.fromLTRB(5.0, 10.0, 5.0, 0.0),
          child: Column(
              children: [
                Container(
                      width: 100,
                      height: 100,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: Colors.red
                      ),
                    ),
                Text('nama'),
                Row(children:[
                  SizedBox(width: 10.0),
                  Icon(Icons.edit),
                  TextButton(onPressed: (){}, child: Text('Edit Profil'))
                ]),
                Row(
                    children:[
                      SizedBox(width: 10.0),
                      Icon(Icons.shop_two),
                      TextButton(onPressed: () {}, child: Text('Daftar sebagai supplier sampah baru'))
                    ]
                ),
                Row(
                  children: [
                    SizedBox(width: 10.0,),
                    Text('Tentang'),
                  ],
                ),
                Row(children:[
                  SizedBox(width: 10.0),
                  Icon(Icons.assignment_late),
                  TextButton(onPressed: () {Navigator.push(context, PageTransition(type: PageTransitionType.fade, child: Panduan()));}, child: Text('Panduan'))
                ]),
                Divider(color: Colors.black,),
                Row(
                    children:[
                      SizedBox(width: 10.0),
                      Icon(Icons.article),
                      TextButton(onPressed: (){Navigator.push(context, PageTransition(type: PageTransitionType.fade, child: Syarat()));}, child: Text('Syarat dan Ketentuan'))
                    ]
                ),
                Divider(color: Colors.black,),
                Row(children:[
                  SizedBox(width: 10.0),
                  Icon(Icons.lock_outline_rounded),
                  TextButton(onPressed: (){Navigator.push(context, PageTransition(type: PageTransitionType.fade, child: Kebijakan()));}, child: Text('Kebijakan Privasi'))
                ]),
                Divider(color: Colors.black,),
                Row(
                    children:[
                      SizedBox(width: 10.0),
                      Icon(Icons.all_inbox),
                      TextButton(onPressed: (){Navigator.push(context, PageTransition(type: PageTransitionType.fade, child: Faq()));}, child: Text('Pertanyaan Umum'))
                    ]
                ),
                Row(children: [SizedBox(width: 10.0),Text('Lainnya')],),
                SizedBox(height: 12.0,),
                Row(children:[
                  SizedBox(width: 10.0),
                  Icon(Icons.android_outlined),
                  SizedBox(width: 7.0),
                  Text('Versi App                                                                   1.0.0',
                  style: TextStyle(
                    color: Colors.blueAccent
                  ),)
                ]),
                Divider(color: Colors.black,),
                Row(
                    children:[
                      SizedBox(width: 10.0),
                      Icon(Icons.exit_to_app),
                      TextButton(onPressed: (){
                        Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (context) =>
                            AuthScreen()), (Route<dynamic> route) => false);
                      }, child: Text('Log Out'))
                    ]
                ),
              ],
            ),
        ),
      ),
    );
  }

}`

**Comment by pedromassango** [comment]
Hi @ricky20121981 
Not sure if In understood this issue correctly, but, if you are trying to remove the Bottom navigation bar, you can just set the `bottomNavigationBar` parameter to null.

Not sure how this is related to this package. I'm closing this for now, please let me know if I missed anything.
Thank you
