### ISSUE TITLE
no attribute "current_index" so navigation does not occur.

### ISSUE THREAD

**Issue by Akshiiitsaxena** [pedromassango/titled_navigation_bar#6]

**Comment by pedromassango** [comment]
Please provide more details

**Comment by Akshiiitsaxena** [comment]
There is no "current index" attribute in the constructor. Because of that I
am unable to change the tab when I tap on a different tab.
It shows the changes in the bottom bar. However the main screen remains the
same

**Comment by BoomPowbep** [comment]
@pedromassango Can you please provide an example showing how to do navigation with the Titled Navigation Bar? As @Akshiiitsaxena said, there is no explicit way of getting it to work because, as opposed to `BottomNAvigationBar`, there is no `currentIndex` parameter...

**Comment by pedromassango** [comment]
I added the `currentIndex `property to updated the Bar by giving an index. Check the latest version
